config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'site#index'
  get 'site/index'
  get 'site/test'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  authenticate :user do
    mount Resque::Server, at: '/jobs'
  end
  resources :bookmarks
  resources :feeds
  resources :items
  namespace :api do
    namespace :v1 do
      resources :bookmarks
      resources :feeds
      resources :items
      resources :profiles
      resources :reactions
      resources :subscriptions
      resources :syndications
      resources :users
    end
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  validates :name, :url, presence: true
  validates :url, uniqueness: {scope: :user_id, case_sensitive: false}
end

app/controllers/api/v1/bookmarks_controller.rb
module Api
  module V1
    class BookmarksController < ApiController
      def index
        bookmarks = BookmarkResource.all(params)
        respond_with(bookmarks)
      end
    
      def show
        bookmark = BookmarkResource.find(params)
        respond_with(bookmark)
      end
    
      def create
        bookmark = BookmarkResource.build(params)
    
        if bookmark.save
          render jsonapi: bookmark, status: 201
        else
          render jsonapi_errors: bookmark
        end
      end
    
      def update
        bookmark = BookmarkResource.find(params)
    
        if bookmark.update_attributes
          render jsonapi: bookmark
        else
          render jsonapi_errors: bookmark
        end
      end
    
      def destroy
        bookmark = BookmarkResource.find(params)
    
        if bookmark.destroy
          render jsonapi: { meta: {} }, status: 200
        else
          render jsonapi_errors: bookmark
        end
      end
    end
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    # @bookmarks = Bookmark.all
    @bookmarks = current_user.bookmarks.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      # @bookmark = Bookmark.find(params[:id])
      @bookmark = current_user.bookmarks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmark_params
      params.require(:bookmark).permit(:user_id, :name, :url, tags: []).merge(user_id: current_user.id)
    end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark, local: true) do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
        <% bookmark.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.url_field :url %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags, name: 'bookmark[tags][]' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookmarks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Url</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.user_id %></td>
        <td><%= bookmark.name %></td>
        <td><%= bookmark.url %></td>
        <td><%= bookmark.tags %></td>
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

<hr>

<div id='bookmarks'>
  {{message}}
  <bookmarks></bookmarks>
</div>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @bookmark.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @bookmark.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @bookmark.tags %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>