config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'site#index'
  get 'site/index'
  get 'site/test'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  authenticate :user do
    mount Resque::Server, at: '/jobs'
  end
  resources :bookmarks
  resources :feeds
  resources :items
  namespace :api do
    namespace :v1 do
      resources :bookmarks
      resources :feeds
      resources :items
      resources :profiles
      resources :reactions
      resources :subscriptions
      resources :syndications
      resources :users
    end
  end
end

app/models/feed.rb
# frozen_string_literal: true

# Feed
class Feed < ApplicationRecord
  # class_attribute :base_url, instance_writer: false, default: 'http://api.spa.test/'
  # Feed.base_url = 'http://api.spa.test/'

  after_create_commit do
    ParseFeedJob.perform_later(self) unless url.starts_with?('/')
  end
  belongs_to :profile, optional: true
  has_many :syndications
  has_many :items, through: :syndications
  has_many :subscriptions
  validates :url, uniqueness: true, url: { no_local: true, public_suffix: true, schemes: %w[http https] }

  def ingest_feed(parsed)
    # keys = %i[format title summary generator updated published]
    # assign_attributes(JSON.parse(parsed.to_json).slice(*keys))
    self.format = parsed.format
    self.title = parsed.title
    self.summary = parsed.summary
    self.generator = parsed.generator
    self.updated = parsed.updated
    self.published = parsed.published
    self.authors = parsed.authors.to_json
    self.tags = parsed.tags.to_json
    initialize_profile
    # save!
    ingest_items(parsed.items)
  end

  def ingest_items(parsed_items)
    parsed_items.each do |parsed_item|
      item = Item.find_or_initialize_by(guid: parsed_item.url)
      # keys = %i[external_url title summary updated published content_html content_text attachments]
      # item.assign_attributes(JSON.parse(parsed_item.to_json).slice(*keys))
      item.ingest_item(parsed_item)
      item.profile = profile if item.profile.nil?
      item.save!
      # feeds << feed unless feeds.include?(feed)
      items << item unless items.include?(item)
    end
  end

  # def initialize
  #   @base_url = 'http://api.spa.test/'
  #   super
  # end

  def initialize_profile
    self.profile = Profile.find_or_initialize_by(url: url) if profile.nil?
    # self.profile.user = user
    profile.user_id = 1 if profile.user_id.nil?
    profile.name = title if profile.name.nil?
    profile.save!
    subscription = Subscription.find_or_initialize_by(profile_id: profile.id, feed_id: id)
    subscription.save!
  end
end

app/controllers/api/v1/feeds_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # FeedsController
    class FeedsController < ApiController
      # after_action :parse_feed, only: [:create]
      def index
        feeds = FeedResource.all(params)
        respond_with(feeds)
      end

      def show
        feed = FeedResource.find(params)
        respond_with(feed)
      end

      def create
        feed = FeedResource.build(params)

        if feed.save
          render jsonapi: feed, status: 201
          # ParseFeedJob.perform_later(feed) unless feed.url.starts_with?('/')
        else
          render jsonapi_errors: feed
        end
      end

      def update
        feed = FeedResource.find(params)

        if feed.update_attributes
          render jsonapi: feed
        else
          render jsonapi_errors: feed
        end
      end

      def destroy
        feed = FeedResource.find(params)

        if feed.destroy
          render jsonapi: { meta: {} }, status: 200
        else
          render jsonapi_errors: feed
        end
      end

      # private

      # def parse_feed
      #   ParseFeedJob.perform_later(feed) unless feed.url.starts_with?('/')
      # end
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feed_params
      params.require(:feed).permit(:url, :format, :title, :summary, :generator, :updated, :published, :authors, :tags)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% feed.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :format %>
    <%= form.text_field :format %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary %>
  </div>

  <div class="field">
    <%= form.label :generator %>
    <%= form.text_field :generator %>
  </div>

  <div class="field">
    <%= form.label :updated %>
    <%= form.datetime_select :updated %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.datetime_select :published %>
  </div>

  <div class="field">
    <%= form.label :authors %>
    <%= form.text_area :authors %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_area :tags %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Format</th>
      <th>Title</th>
      <th>Summary</th>
      <th>Generator</th>
      <th>Updated</th>
      <th>Published</th>
      <th>Authors</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.url %></td>
        <td><%= feed.format %></td>
        <td><%= feed.title %></td>
        <td><%= feed.summary %></td>
        <td><%= feed.generator %></td>
        <td><%= feed.updated %></td>
        <td><%= feed.published %></td>
        <td><%= feed.authors %></td>
        <td><%= feed.tags %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Format:</strong>
  <%= @feed.format %>
</p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @feed.summary %>
</p>

<p>
  <strong>Generator:</strong>
  <%= @feed.generator %>
</p>

<p>
  <strong>Updated:</strong>
  <%= @feed.updated %>
</p>

<p>
  <strong>Published:</strong>
  <%= @feed.published %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @feed.authors %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @feed.tags %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>