config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'site#index'
  get 'site/index'
  get 'site/test'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  authenticate :user do
    mount Resque::Server, at: '/jobs'
  end
  resources :bookmarks
  resources :feeds
  resources :items
  namespace :api do
    namespace :v1 do
      resources :bookmarks
      resources :feeds
      resources :items
      resources :profiles
      resources :reactions
      resources :subscriptions
      resources :syndications
      resources :users
    end
  end
end

app/views/layouts/application.html.erb
<% content_for :head do %>
    <%#= javascript_pack_tag 'hello_vue' %>
    <%#= stylesheet_pack_tag 'hello_vue' %>
<% end %>
<!DOCTYPE html>
<html>
  <head>
    <title>Experiments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :head %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div>
      <%= link_to 'Home', root_path %>
      <%= link_to 'Bookmarks', bookmarks_path %>
      <%= link_to 'Jobs', '/jobs' %>
      <%= link_to 'site/test', site_test_path %>
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      <% else %>
        Welcome, user
        <%= link_to 'Sign in', new_user_session_path %>
      <% end %>
    </div>
    <hr>
    <%= content_for?(:content) ? yield(:content) : yield %>
    <hr>
    <p>session: <%#= session.to_json %></p>
    <p>user_session: <%#= user_session %></p>
    <hr>
  </body>
</html>

app/views/layouts/bookmarks.html.erb
<% content_for :head do %>
  <%= javascript_pack_tag 'bookmarks' %>
<% end %>

<% content_for :content do %>
  <%= yield %>
<% end %>

<%= render template: "layouts/application" %>